previews:
  generation: automatic

services:
  - type: web
    name: web
    plan: free
    runtime: node
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: playground
    plan: free
    runtime: node
    envVars:
      - key: NODE_ENV
        value: production
  - type: web
    name: api
    plan: free
    runtime: node
    envVars:
      - key: NODE_ENV
        value: production
