services:
  # MongoDB - You should set up a real MongoDB Atlas database
  # This is just a placeholder - you'll need to replace with your own MongoDB URL in the Render.com dashboard

  # Gateway Service
  - type: web
    name: gateway
    plan: free
    runtime: docker
    rootDir: .
    dockerfilePath: apps/gateway/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_BASE_URL
        value: https://api-3bj5.onrender.com
      - key: WEB_URL
        value: https://web-service.onrender.com
      - key: VITE_API_BASE_URL
        value: https://api-3bj5.onrender.com
      - key: VITE_WEB_URL
        value: https://web-service.onrender.com
      - key: GATEWAY_API_KEY
        value: 'render-gateway-api-key-0123456789abcdef0123456789abcdef'
  - type: web
    name: web
    plan: free
    runtime: docker
    rootDir: .
    dockerfilePath: apps/web/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_BASE_URL
        value: https://api-3bj5.onrender.com
      - key: VITE_API_BASE_URL
        value: https://api-3bj5.onrender.com
      - key: DOCS_URL
        value: https://opendatacapture.org/docs
      - key: GITHUB_REPO_URL
        value: https://github.com/DouglasNeuroInformatics/OpenDataCapture
      - key: GATEWAY_ENABLED
        value: 'true'
      - key: CONTACT_EMAIL
        value: 'info@example.com'
      - key: LICENSE_URL
        value: 'https://github.com/DouglasNeuroInformatics/OpenDataCapture/blob/main/LICENSE'
      - key: PLAUSIBLE_BASE_URL
        value: 'https://plausible.io'
      - key: PLAUSIBLE_WEB_DATA_DOMAIN
        value: 'opendatacapture.org'

  - type: web
    name: playground
    plan: free
    runtime: docker
    rootDir: .
    dockerfilePath: apps/playground/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: api
    plan: free
    runtime: docker
    rootDir: .
    dockerfilePath: apps/api/Dockerfile
    healthCheckPath: /v1/health
    envVars:
      - key: VERSION
        value: latest
      - key: NODE_ENV
        value: production
      - key: SECRET_KEY
        sync: false
      - key: GATEWAY_API_KEY
        value: 'render-gateway-api-key-0123456789abcdef0123456789abcdef'
      # MongoDB connection - use a real MongoDB Atlas URL
      - key: MONGO_URI
        sync: false
      # PostgreSQL connection - use a real PostgreSQL URL
      - key: GATEWAY_DATABASE_URL
        sync: false
      - key: GATEWAY_ENABLED
        value: 'true'
      - key: GATEWAY_REFRESH_INTERVAL
        value: '300000'
      - key: GATEWAY_SITE_ADDRESS
        value: https://gateway-service.onrender.com
